// Code generated by counterfeiter. DO NOT EDIT.
package dbfakes

import (
	"context"
	"sync"
	"time"

	lager "code.cloudfoundry.org/lager/v3"
	"code.cloudfoundry.org/locket/db"
)

type FakeLocketHealthCheckDB struct {
	PerformLocketHealthCheckStub        func(context.Context, lager.Logger, time.Time) error
	performLocketHealthCheckMutex       sync.RWMutex
	performLocketHealthCheckArgsForCall []struct {
		arg1 context.Context
		arg2 lager.Logger
		arg3 time.Time
	}
	performLocketHealthCheckReturns struct {
		result1 error
	}
	performLocketHealthCheckReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeLocketHealthCheckDB) PerformLocketHealthCheck(arg1 context.Context, arg2 lager.Logger, arg3 time.Time) error {
	fake.performLocketHealthCheckMutex.Lock()
	ret, specificReturn := fake.performLocketHealthCheckReturnsOnCall[len(fake.performLocketHealthCheckArgsForCall)]
	fake.performLocketHealthCheckArgsForCall = append(fake.performLocketHealthCheckArgsForCall, struct {
		arg1 context.Context
		arg2 lager.Logger
		arg3 time.Time
	}{arg1, arg2, arg3})
	stub := fake.PerformLocketHealthCheckStub
	fakeReturns := fake.performLocketHealthCheckReturns
	fake.recordInvocation("PerformLocketHealthCheck", []interface{}{arg1, arg2, arg3})
	fake.performLocketHealthCheckMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeLocketHealthCheckDB) PerformLocketHealthCheckCallCount() int {
	fake.performLocketHealthCheckMutex.RLock()
	defer fake.performLocketHealthCheckMutex.RUnlock()
	return len(fake.performLocketHealthCheckArgsForCall)
}

func (fake *FakeLocketHealthCheckDB) PerformLocketHealthCheckCalls(stub func(context.Context, lager.Logger, time.Time) error) {
	fake.performLocketHealthCheckMutex.Lock()
	defer fake.performLocketHealthCheckMutex.Unlock()
	fake.PerformLocketHealthCheckStub = stub
}

func (fake *FakeLocketHealthCheckDB) PerformLocketHealthCheckArgsForCall(i int) (context.Context, lager.Logger, time.Time) {
	fake.performLocketHealthCheckMutex.RLock()
	defer fake.performLocketHealthCheckMutex.RUnlock()
	argsForCall := fake.performLocketHealthCheckArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeLocketHealthCheckDB) PerformLocketHealthCheckReturns(result1 error) {
	fake.performLocketHealthCheckMutex.Lock()
	defer fake.performLocketHealthCheckMutex.Unlock()
	fake.PerformLocketHealthCheckStub = nil
	fake.performLocketHealthCheckReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeLocketHealthCheckDB) PerformLocketHealthCheckReturnsOnCall(i int, result1 error) {
	fake.performLocketHealthCheckMutex.Lock()
	defer fake.performLocketHealthCheckMutex.Unlock()
	fake.PerformLocketHealthCheckStub = nil
	if fake.performLocketHealthCheckReturnsOnCall == nil {
		fake.performLocketHealthCheckReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.performLocketHealthCheckReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeLocketHealthCheckDB) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeLocketHealthCheckDB) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ db.LocketHealthCheckDB = new(FakeLocketHealthCheckDB)
