// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: locket.proto

package models

import (
	_ "code.cloudfoundry.org/bbs/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoTypeCode int32

const (
	ProtoTypeCode_UNKNOWN  ProtoTypeCode = 0
	ProtoTypeCode_LOCK     ProtoTypeCode = 1
	ProtoTypeCode_PRESENCE ProtoTypeCode = 2
)

// Enum value maps for ProtoTypeCode.
var (
	ProtoTypeCode_name = map[int32]string{
		0: "UNKNOWN",
		1: "LOCK",
		2: "PRESENCE",
	}
	ProtoTypeCode_value = map[string]int32{
		"UNKNOWN":  0,
		"LOCK":     1,
		"PRESENCE": 2,
	}
)

func (x ProtoTypeCode) Enum() *ProtoTypeCode {
	p := new(ProtoTypeCode)
	*p = x
	return p
}

func (x ProtoTypeCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoTypeCode) Descriptor() protoreflect.EnumDescriptor {
	return file_locket_proto_enumTypes[0].Descriptor()
}

func (ProtoTypeCode) Type() protoreflect.EnumType {
	return &file_locket_proto_enumTypes[0]
}

func (x ProtoTypeCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtoTypeCode.Descriptor instead.
func (ProtoTypeCode) EnumDescriptor() ([]byte, []int) {
	return file_locket_proto_rawDescGZIP(), []int{0}
}

type ProtoResource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Owner string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Value string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Deprecated: Marked as deprecated in locket.proto.
	Type          string        `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	TypeCode      ProtoTypeCode `protobuf:"varint,5,opt,name=type_code,json=typeCode,proto3,enum=models.ProtoTypeCode" json:"type_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoResource) Reset() {
	*x = ProtoResource{}
	mi := &file_locket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoResource) ProtoMessage() {}

func (x *ProtoResource) ProtoReflect() protoreflect.Message {
	mi := &file_locket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoResource.ProtoReflect.Descriptor instead.
func (*ProtoResource) Descriptor() ([]byte, []int) {
	return file_locket_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoResource) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProtoResource) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ProtoResource) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Deprecated: Marked as deprecated in locket.proto.
func (x *ProtoResource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProtoResource) GetTypeCode() ProtoTypeCode {
	if x != nil {
		return x.TypeCode
	}
	return ProtoTypeCode_UNKNOWN
}

type ProtoLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ProtoResource         `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	TtlInSeconds  int64                  `protobuf:"varint,2,opt,name=ttl_in_seconds,json=ttlInSeconds,proto3" json:"ttl_in_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoLockRequest) Reset() {
	*x = ProtoLockRequest{}
	mi := &file_locket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoLockRequest) ProtoMessage() {}

func (x *ProtoLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoLockRequest.ProtoReflect.Descriptor instead.
func (*ProtoLockRequest) Descriptor() ([]byte, []int) {
	return file_locket_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoLockRequest) GetResource() *ProtoResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ProtoLockRequest) GetTtlInSeconds() int64 {
	if x != nil {
		return x.TtlInSeconds
	}
	return 0
}

type ProtoLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoLockResponse) Reset() {
	*x = ProtoLockResponse{}
	mi := &file_locket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoLockResponse) ProtoMessage() {}

func (x *ProtoLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_locket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoLockResponse.ProtoReflect.Descriptor instead.
func (*ProtoLockResponse) Descriptor() ([]byte, []int) {
	return file_locket_proto_rawDescGZIP(), []int{2}
}

type ProtoReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ProtoResource         `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoReleaseRequest) Reset() {
	*x = ProtoReleaseRequest{}
	mi := &file_locket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoReleaseRequest) ProtoMessage() {}

func (x *ProtoReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoReleaseRequest.ProtoReflect.Descriptor instead.
func (*ProtoReleaseRequest) Descriptor() ([]byte, []int) {
	return file_locket_proto_rawDescGZIP(), []int{3}
}

func (x *ProtoReleaseRequest) GetResource() *ProtoResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ProtoReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoReleaseResponse) Reset() {
	*x = ProtoReleaseResponse{}
	mi := &file_locket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoReleaseResponse) ProtoMessage() {}

func (x *ProtoReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_locket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoReleaseResponse.ProtoReflect.Descriptor instead.
func (*ProtoReleaseResponse) Descriptor() ([]byte, []int) {
	return file_locket_proto_rawDescGZIP(), []int{4}
}

type ProtoFetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoFetchRequest) Reset() {
	*x = ProtoFetchRequest{}
	mi := &file_locket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoFetchRequest) ProtoMessage() {}

func (x *ProtoFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoFetchRequest.ProtoReflect.Descriptor instead.
func (*ProtoFetchRequest) Descriptor() ([]byte, []int) {
	return file_locket_proto_rawDescGZIP(), []int{5}
}

func (x *ProtoFetchRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ProtoFetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ProtoResource         `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoFetchResponse) Reset() {
	*x = ProtoFetchResponse{}
	mi := &file_locket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoFetchResponse) ProtoMessage() {}

func (x *ProtoFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_locket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoFetchResponse.ProtoReflect.Descriptor instead.
func (*ProtoFetchResponse) Descriptor() ([]byte, []int) {
	return file_locket_proto_rawDescGZIP(), []int{6}
}

func (x *ProtoFetchResponse) GetResource() *ProtoResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ProtoFetchAllRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in locket.proto.
	Type          string        `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TypeCode      ProtoTypeCode `protobuf:"varint,2,opt,name=type_code,json=typeCode,proto3,enum=models.ProtoTypeCode" json:"type_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoFetchAllRequest) Reset() {
	*x = ProtoFetchAllRequest{}
	mi := &file_locket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoFetchAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoFetchAllRequest) ProtoMessage() {}

func (x *ProtoFetchAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoFetchAllRequest.ProtoReflect.Descriptor instead.
func (*ProtoFetchAllRequest) Descriptor() ([]byte, []int) {
	return file_locket_proto_rawDescGZIP(), []int{7}
}

// Deprecated: Marked as deprecated in locket.proto.
func (x *ProtoFetchAllRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProtoFetchAllRequest) GetTypeCode() ProtoTypeCode {
	if x != nil {
		return x.TypeCode
	}
	return ProtoTypeCode_UNKNOWN
}

type ProtoFetchAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*ProtoResource       `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoFetchAllResponse) Reset() {
	*x = ProtoFetchAllResponse{}
	mi := &file_locket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoFetchAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoFetchAllResponse) ProtoMessage() {}

func (x *ProtoFetchAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_locket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoFetchAllResponse.ProtoReflect.Descriptor instead.
func (*ProtoFetchAllResponse) Descriptor() ([]byte, []int) {
	return file_locket_proto_rawDescGZIP(), []int{8}
}

func (x *ProtoFetchAllResponse) GetResources() []*ProtoResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

var File_locket_proto protoreflect.FileDescriptor

const file_locket_proto_rawDesc = "" +
	"\n" +
	"\flocket.proto\x12\x06models\x1a\tbbs.proto\"\x99\x01\n" +
	"\rProtoResource\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x04type\x18\x04 \x01(\tB\x02\x18\x01R\x04type\x122\n" +
	"\ttype_code\x18\x05 \x01(\x0e2\x15.models.ProtoTypeCodeR\btypeCode\"k\n" +
	"\x10ProtoLockRequest\x121\n" +
	"\bresource\x18\x01 \x01(\v2\x15.models.ProtoResourceR\bresource\x12$\n" +
	"\x0ettl_in_seconds\x18\x02 \x01(\x03R\fttlInSeconds\"\x13\n" +
	"\x11ProtoLockResponse\"H\n" +
	"\x13ProtoReleaseRequest\x121\n" +
	"\bresource\x18\x01 \x01(\v2\x15.models.ProtoResourceR\bresource\"\x16\n" +
	"\x14ProtoReleaseResponse\"%\n" +
	"\x11ProtoFetchRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"G\n" +
	"\x12ProtoFetchResponse\x121\n" +
	"\bresource\x18\x01 \x01(\v2\x15.models.ProtoResourceR\bresource\"b\n" +
	"\x14ProtoFetchAllRequest\x12\x16\n" +
	"\x04type\x18\x01 \x01(\tB\x02\x18\x01R\x04type\x122\n" +
	"\ttype_code\x18\x02 \x01(\x0e2\x15.models.ProtoTypeCodeR\btypeCode\"L\n" +
	"\x15ProtoFetchAllResponse\x123\n" +
	"\tresources\x18\x01 \x03(\v2\x15.models.ProtoResourceR\tresources*V\n" +
	"\rProtoTypeCode\x12\x17\n" +
	"\aUNKNOWN\x10\x00\x1a\n" +
	"\x82}\aUNKNOWN\x12\x11\n" +
	"\x04LOCK\x10\x01\x1a\a\x82}\x04LOCK\x12\x19\n" +
	"\bPRESENCE\x10\x02\x1a\v\x82}\bPRESENCE2\xb5\x02\n" +
	"\vProtoLocket\x12B\n" +
	"\tProtoLock\x12\x18.models.ProtoLockRequest\x1a\x19.models.ProtoLockResponse\"\x00\x12E\n" +
	"\n" +
	"ProtoFetch\x12\x19.models.ProtoFetchRequest\x1a\x1a.models.ProtoFetchResponse\"\x00\x12K\n" +
	"\fProtoRelease\x12\x1b.models.ProtoReleaseRequest\x1a\x1c.models.ProtoReleaseResponse\"\x00\x12N\n" +
	"\rProtoFetchAll\x12\x1c.models.ProtoFetchAllRequest\x1a\x1d.models.ProtoFetchAllResponse\"\x00B%Z#code.cloudfoundry.org/locket/modelsb\x06proto3"

var (
	file_locket_proto_rawDescOnce sync.Once
	file_locket_proto_rawDescData []byte
)

func file_locket_proto_rawDescGZIP() []byte {
	file_locket_proto_rawDescOnce.Do(func() {
		file_locket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_locket_proto_rawDesc), len(file_locket_proto_rawDesc)))
	})
	return file_locket_proto_rawDescData
}

var file_locket_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_locket_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_locket_proto_goTypes = []any{
	(ProtoTypeCode)(0),            // 0: models.ProtoTypeCode
	(*ProtoResource)(nil),         // 1: models.ProtoResource
	(*ProtoLockRequest)(nil),      // 2: models.ProtoLockRequest
	(*ProtoLockResponse)(nil),     // 3: models.ProtoLockResponse
	(*ProtoReleaseRequest)(nil),   // 4: models.ProtoReleaseRequest
	(*ProtoReleaseResponse)(nil),  // 5: models.ProtoReleaseResponse
	(*ProtoFetchRequest)(nil),     // 6: models.ProtoFetchRequest
	(*ProtoFetchResponse)(nil),    // 7: models.ProtoFetchResponse
	(*ProtoFetchAllRequest)(nil),  // 8: models.ProtoFetchAllRequest
	(*ProtoFetchAllResponse)(nil), // 9: models.ProtoFetchAllResponse
}
var file_locket_proto_depIdxs = []int32{
	0,  // 0: models.ProtoResource.type_code:type_name -> models.ProtoTypeCode
	1,  // 1: models.ProtoLockRequest.resource:type_name -> models.ProtoResource
	1,  // 2: models.ProtoReleaseRequest.resource:type_name -> models.ProtoResource
	1,  // 3: models.ProtoFetchResponse.resource:type_name -> models.ProtoResource
	0,  // 4: models.ProtoFetchAllRequest.type_code:type_name -> models.ProtoTypeCode
	1,  // 5: models.ProtoFetchAllResponse.resources:type_name -> models.ProtoResource
	2,  // 6: models.ProtoLocket.ProtoLock:input_type -> models.ProtoLockRequest
	6,  // 7: models.ProtoLocket.ProtoFetch:input_type -> models.ProtoFetchRequest
	4,  // 8: models.ProtoLocket.ProtoRelease:input_type -> models.ProtoReleaseRequest
	8,  // 9: models.ProtoLocket.ProtoFetchAll:input_type -> models.ProtoFetchAllRequest
	3,  // 10: models.ProtoLocket.ProtoLock:output_type -> models.ProtoLockResponse
	7,  // 11: models.ProtoLocket.ProtoFetch:output_type -> models.ProtoFetchResponse
	5,  // 12: models.ProtoLocket.ProtoRelease:output_type -> models.ProtoReleaseResponse
	9,  // 13: models.ProtoLocket.ProtoFetchAll:output_type -> models.ProtoFetchAllResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_locket_proto_init() }
func file_locket_proto_init() {
	if File_locket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_locket_proto_rawDesc), len(file_locket_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_locket_proto_goTypes,
		DependencyIndexes: file_locket_proto_depIdxs,
		EnumInfos:         file_locket_proto_enumTypes,
		MessageInfos:      file_locket_proto_msgTypes,
	}.Build()
	File_locket_proto = out.File
	file_locket_proto_goTypes = nil
	file_locket_proto_depIdxs = nil
}
